# USE DIFFERENT CONDA ENV - NETCDF conda env

In [4]:
from pydoc import text

import numpy as np
import pandas as pd
import xarray as xr
import os
np.random.seed(42)


import warnings
warnings.filterwarnings('ignore')

In [28]:
test_data = xr.open_dataset("./data/Modtran6_data/FV3_Modtran6_IO_v4_scene_1.nc")
test_data2 = xr.open_dataset("./data/Modtran6_data/FV3_Modtran6_IO_v4_scene_2.nc")
test_data

<xarray.Dataset> Size: 358MB
Dimensions:                                                              (
                                                                          erbe_relative_azimuth_angle: 8,
                                                                          erbe_solar_zenith_angle: 10,
                                                                          erbe_viewing_zenith_angle: 7,
                                                                          ceres_trmm_relative_azimuth_angle: 10,
                                                                          ceres_trmm_solar_zenith_angle: 9,
                                                                          ...
                                                                          Levels: 31,
                                                                          modis_brdf_parameter: 3,
                                                                          modis_brdf_band: 7,
                                                                          wavelength_sw: 1901,
                                                                          wavelength_lw: 391,
                                                                          wavenumber: 2664)
Coordinates:
  * wavelength_sw                                                        (wavelength_sw) float64 15kB ...
  * wavelength_lw                                                        (wavelength_lw) float64 3kB ...
  * wavenumber                                                           (wavenumber) float64 21kB ...
Dimensions without coordinates: erbe_relative_azimuth_angle,
                                erbe_solar_zenith_angle,
                                erbe_viewing_zenith_angle,
                                ceres_trmm_relative_azimuth_angle,
                                ceres_trmm_solar_zenith_angle,
                                ceres_trmm_viewing_zenith_angle, Levels,
                                modis_brdf_parameter, modis_brdf_band
Data variables: (12/121)
    ERBE_RAA                                                             (erbe_relative_azimuth_angle) float64 64B ...
    ERBE_SZA                                                             (erbe_solar_zenith_angle) float64 80B ...
    ERBE_VZA                                                             (erbe_viewing_zenith_angle) float64 56B ...
    CERES_TRMM_RAA                                                       (ceres_trmm_relative_azimuth_angle) float64 80B ...
    CERES_TRMM_SZA                                                       (ceres_trmm_solar_zenith_angle) float64 72B ...
    CERES_TRMM_VZA                                                       (ceres_trmm_viewing_zenith_angle) float64 72B ...
    ...                                                                   ...
    MODTRAN6_TOT_RAD_TOA_CERES-TRMM                                      (ceres_trmm_relative_azimuth_angle, ceres_trmm_solar_zenith_angle, ceres_trmm_viewing_zenith_angle) float64 6kB ...
    MODTRAN6_TOT_FLX_UPDIF_CERES-TRMM                                    (ceres_trmm_solar_zenith_angle, Levels) float64 2kB ...
    MODTRAN6_TOT_FLX_DNDIF_CERES-TRMM                                    (ceres_trmm_solar_zenith_angle, Levels) float64 2kB ...
    MODTRAN6_TOT_FLX_DNDIR_CERES-TRMM                                    (ceres_trmm_solar_zenith_angle, Levels) float64 2kB ...
    MODTRAN6_550NM_RAD_TOA_CERES-TRMM                                    (ceres_trmm_relative_azimuth_angle, ceres_trmm_solar_zenith_angle, ceres_trmm_viewing_zenith_angle) float64 6kB ...
    MODTRAN6_550NM_DNFLX_TOA_CERES-TRMM                                  (ceres_trmm_solar_zenith_angle) float64 72B ...
Attributes:
    Description:    Libera Modtran6 FV3 OSSE Inputs and Outputs for Single Da...
    Creation_Date:  05-Oct-2025 11:44:07

In [13]:
test_data["IGBP_Type"].data

numpy.ndarray

In [29]:
erbe_raa = test_data["ERBE_RAA"]


sw_erbe = test_data["MODTRAN6_SPECTRAL_RADIANCE_TOA_SW_WVL_ERBE"]
lw_erbe = test_data["MODTRAN6_SPECTRAL_RADIANCE_TOA_LW_WVL_ERBE"]
sw_ct = test_data["MODTRAN6_SPECTRAL_RADIANCE_TOA_SW_WVL_CERES_TRMM"]
lw_ct = test_data["MODTRAN6_SPECTRAL_RADIANCE_TOA_LW_WVL_CERES_TRMM"]

sw_erbe2 = test_data2["MODTRAN6_SPECTRAL_RADIANCE_TOA_SW_WVL_ERBE"]
lw_erbe2 = test_data2["MODTRAN6_SPECTRAL_RADIANCE_TOA_LW_WVL_ERBE"]
sw_ct2 = test_data2["MODTRAN6_SPECTRAL_RADIANCE_TOA_SW_WVL_CERES_TRMM"]
lw_ct2 = test_data2["MODTRAN6_SPECTRAL_RADIANCE_TOA_LW_WVL_CERES_TRMM"]

In [24]:
sw_erbe.to_dataframe()

                                                                                             MODTRAN6_SPECTRAL_RADIANCE_TOA_SW_WVL_ERBE
erbe_viewing_zenith_angle erbe_solar_zenith_angle erbe_relative_azimuth_angle wavelength_sw
0                         0                       0                           250.0                                                 NaN
                                                                              252.5                                        4.442522e-10
                                                                              255.0                                        7.282273e-10
                                                                              257.5                                        1.256321e-09
                                                                              260.0                                        9.956883e-10
...                                                                                                                                 ...
6                         9                       7                           4990.0                                       5.829055e-08
                                                                              4992.5                                       5.828931e-08
                                                                              4995.0                                       5.828807e-08
                                                                              4997.5                                       5.828684e-08
                                                                              5000.0                                       5.828560e-08

[1064560 rows x 1 columns]

In [26]:
erbe_raa.to_dataframe()

                             ERBE_RAA
erbe_relative_azimuth_angle
0                                 4.5
1                                19.5
2                                45.0
3                                75.0
4                               105.0
5                               135.0
6                               160.5
7                               175.5

In [27]:
sw_ct.to_dataframe()

                                                                                                               MODTRAN6_SPECTRAL_RADIANCE_TOA_SW_WVL_CERES_TRMM
ceres_trmm_viewing_zenith_angle ceres_trmm_solar_zenith_angle ceres_trmm_relative_azimuth_angle wavelength_sw
0                               0                             0                                 250.0                                                       NaN
                                                                                                252.5                                              4.685684e-10
                                                                                                255.0                                              7.681132e-10
                                                                                                257.5                                              1.325109e-09
                                                                                                260.0                                              1.050148e-09
...                                                                                                                                                         ...
8                               8                             9                                 4990.0                                             1.320270e-07
                                                                                                4992.5                                             1.326409e-07
                                                                                                4995.0                                             1.332549e-07
                                                                                                4997.5                                             1.338688e-07
                                                                                                5000.0                                             1.344828e-07

[1539810 rows x 1 columns]

In [30]:
sw_erbe2.to_dataframe()

                                                                                             MODTRAN6_SPECTRAL_RADIANCE_TOA_SW_WVL_ERBE
erbe_viewing_zenith_angle erbe_solar_zenith_angle erbe_relative_azimuth_angle wavelength_sw
0                         0                       0                           250.0                                                 NaN
                                                                              252.5                                        4.397695e-10
                                                                              255.0                                        7.214624e-10
                                                                              257.5                                        1.245185e-09
                                                                              260.0                                        9.808596e-10
...                                                                                                                                 ...
6                         9                       7                           4990.0                                       1.079574e-07
                                                                              4992.5                                       1.081190e-07
                                                                              4995.0                                       1.082805e-07
                                                                              4997.5                                       1.084421e-07
                                                                              5000.0                                       1.086036e-07

[1064560 rows x 1 columns]